### ISSUE TITLE
Consider adding UI Playbook

### ISSUE THREAD

**Issue by raunofreiberg** [ComponentDriven/componentdriven.org#17]
Hey,

First of all. Great initiative and superb design!

I thought maybe it'd make sense to add [UI Playbook](http://uiplaybook.dev/) to either the list of tools or "learn more" section on the site?

Essentially, UI Playbook is a documented collection of common UI components, their functionality, best practices, accessibility requirements, and examples. And, it's fairly implementation agnostic, so the practices are generally applicable!

If this seems fitting, I'd gladly make a PR. If not, keep up the good work! ✌️

**Comment by domyen** [comment]
Thanks for the suggestion @raunofreiberg, UI Playbook looks cool! We're focusing on well-established resources and tools right now. UI Playbook seems really early on in its development so I don't think it fits here.

Again, appreciate your suggestion and thanks for checking the site out 🙇
