### ISSUE TITLE
Consider adding Specify

### ISSUE THREAD

**Issue by valentinchrt** [ComponentDriven/componentdriven.org#18]
Hi folks,

Thanks for the initiative!

I would like to propose [Specify](https://specifyapp.com/) to the list of design tools.

Specify acts as a central platform that enables the continuous collection, centralization and distribution of all UI decisions (design tokens, assets and components) — from design tools to development tools.

We are still in beta but we have hundreds of teams who have been using us for more than a year, and we have lots of exciting things coming up!

My team and I would love to be part of this initiative :)

**Comment by winkerVSbecks** [comment]
Hey @valentinchrt, Specify looks really cool. Actually wouldn't mind trying it out myself. However, this is a curated list and at the moment we are only adding tools that are well-established and production ready (no alpha/beta products).

**Comment by valentinchrt** [comment]
Thanks for your reply @winkerVSbecks!

I totally understand that you don't want to add tools that are currently in alpha/beta, we won't hesitate to contribute when we match your different criteria :)

I'm still a little confused — we've been in the ecosystem for a while (over 2 years), alongside other tools that are on the list and that are not yet open to the public.

I think that's what misled me :)
