### ISSUE TITLE
Adding Stencil.js to the development tools section.

### ISSUE THREAD

**Issue by mabry1985** [ComponentDriven/componentdriven.org#24]
I would love to nominate [Stencil.js](https://stenciljs.com/) to be added to the homepage under development tools. It embodies the component driven methodologies and has a great community and documentation. 

I'm not affiliated with Stencil, I am just a user who really enjoys the tooling.  

Thank you for your consideration.

**Comment by winkerVSbecks** [comment]
@mabry1985 done

**Comment by mabry1985** [comment]
@winkerVSbecks That's great, thanks!
